lrpc:
  config:
    rpcClient: netty
    serviceRegistry: nacos
    serviceProvider: nacos
    serviceDiscovery: nacos
    serialization: kyro
    compress: snappy
    loadBalance: consistentHash
    registryHost: 39.105.219.181

