lrpc:
  config:
    rpcClient: netty
    serviceRegistry: nacos
    serviceProvider: nacos
    serviceDiscovery: nacos
    serialization: kyro
    compress: snappy
    loadBalance: consistentHash
    flowControl: tokenBucket
    qps: 10.0
    failureStrategy: wait
    registryHost: 39.105.219.181
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/database1
    username: root
    password: 123456
